config/routes.rb
CfWhiteboard::Application.routes.draw do

  root :to => 'questions#index'

  resources :questions
  resources :comments do
    collection do
      post 'create_comment'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :question 
	validates_presence_of :content, :user_name, :question_id

	attr_accessible :content, :user_name, :question_id 

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :comments
	validates_presence_of :title, :user_name, :company
	accepts_nested_attributes_for :comments
	
	attr_accessible :title, :user_name, :company, :job_title

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :http_authenticate if Rails.env == "production"

  def http_authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "codefellows" && password == "c0defe!!@ws"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create_comment
		@question = Question.find_by_id(params[:question_id])
		@comment = Comment.new(:content => params[:content],:user_name => params[:user_name],:question_id => @question.id)
		if @comment.save
			redirect_to question_path(@question.id)
		else
			render :template => "questions/show"
		end
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	WillPaginate.per_page = 10

	def index
		@questions = Question.page(params[:page]).order("created_at DESC")
	end

	def show
		@question  = Question.find_by_id(params[:id])
	end

	def new
		@question = Question.new
		@comment = Comment.new
	end

	def edit
		@question = Question.find_by_id(params[:id])	
	end

	def create
		params_comment = params[:question].delete(:comment)
		@question = Question.new(params[:question])
		if @question.save 
			unless params_comment[:content].blank?
				@comment = @question.comments.build(:content => params_comment[:content], :user_name => params[:question][:user_name])
				@comment.save
			end
			redirect_to questions_path
		else
			render :action => "new"
		end
	end

	def update
		@question = Question.find_by_id(params[:id])
		if @question.update_attributes(params[:question]) 
			redirect_to questions_path
		else
			render :action => "edit"
		end
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whiteboard Wizards</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "/stylesheets/bootstrap" %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "/javascripts/nicEdit"%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container" style="padding:70px 0;">
		<div class="row col-lg-12" >
			<div class="navbar navbar-fixed-top">
			<a class="navbar-brand" href="/" style="max-width:250px;padding:9px;"><%=image_tag('logo.png', :style =>"width:30px;")%> Whiteboard Wizards</a>
				<ul class="nav navbar-nav">
			    <li class="<%=params[:action] == 'index' && params[:controller] == 'questions' ? 'active' : '' %>"><a href="/">Interview Question</a></li>
			  	<li class="<%=params[:action] == 'new' && params[:controller] == 'questions' ? 'active' : '' %>"><%=link_to "Add New Question", new_question_path %></li>
			  </ul>
			</div>
			<%= yield %>
		</div>	
	</div>
</body>
</html>

app/views/questions/edit.html.erb
<script type="text/javascript">
bkLib.onDomLoaded(function() {
  new nicEditor({fullPanel : true}).panelInstance('question_title');
});
</script>

<%if !@question.errors.blank? %>
  <div class="alert alert-danger">
    <ul>
      <% @question.errors.full_messages.each do |e|%>
        <li><%= e%></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%=form_for(@question) do |f|%>
  <fieldset style="width: 600px;">
    <legend>Edit Question</legend>
    <div class="form-group">
      <%=f.label :user_name, "Your name" %>
      <%=f.text_field :user_name,:class=>"form-control" %>
    </div>
    <div class="form-group">
      <%=f.label :title%>
      <%=f.text_area :title,:class=>"form-control",:style=>"height:150px;"%>
    </div>

    <div class="form-group">
      <%=f.label :company, "Company name"%>
      <%=f.text_field :company,:class=>"form-control"%>
    </div>

     <div class="form-group">
      <%=f.label :job_title %>
      <%=f.text_field :job_title,:class=>"form-control" %>
    </div>
    
    <%= f.submit "Save",:class => "btn"%>
  </fieldset>
<% end%>

app/views/questions/index.html.erb
<div>
	<h3>Interview Questions</h3>
	<div class="list-group">
	<% @questions.each do |q|%>
	  <div href="<%=question_path(q)%>" class="list-group-item" onclick="window.location.replace('<%=url_for :controller => "questions", :action => "show" ,:id => q.id%>');">
  	  <h4 class="list-group-item-heading"><%=raw q.title%>
  	  	<span class="label" style="font-size:12px;"><%=q.company%></span>
  	  	<% if q.job_title%>
  	  		<span class="label" style="font-size:12px;"><%= q.job_title%></span>
  	  	<% end %>	
  	  <% if q.comments.size == 0 %>
  	  	<span class="label label-success" style="font-size:12px;">0 Answers</span>
  	  <% else %>
  	  	<span class="label label-success" style="font-size:12px;"><%=q.comments.size%> Answers</span>
  	  <% end %>
      <span style="display:block;text-align:right;font-size:12px;"> By: <%=q.user_name%></span>

  	  </h4>
    	<div class="list-group-item-text" ><%=q.comments.first ? (raw q.comments.first.content) : ''%></div>
  	</div>
	<% end %>
	</div>
	<%= will_paginate @questions %>
</div>

app/views/questions/new.html.erb
<script type="text/javascript">
bkLib.onDomLoaded(function() {
  new nicEditor({fullPanel : true}).panelInstance('question_title');
  new nicEditor({fullPanel : true}).panelInstance('question_comment_content');
});
</script>

<%if !@question.errors.blank? %>
  <div class="alert alert-danger">
    <ul>
      <% @question.errors.full_messages.each do |e|%>
        <li><%= e%></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%=form_for(@question) do |f|%>
  <fieldset style="width: 600px;">
    <legend>Create new Question</legend>
    <div class="form-group">
      <%=f.label :user_name, "Your name" %>
      <%=f.text_field :user_name ,:class=>"form-control"%>
    </div>
    <div class="form-group">
      <%=f.label :title,"Question"%>
      <%=f.text_area :title,:class=>"form-control",:style=>"height:150px;"%>
    </div>

    <div class="form-group">
      <%=f.label :company, "Company name"%>
      <%=f.text_field :company,:class=>"form-control"%>
    </div>

     <div class="form-group">
      <%=f.label :job_title %>
      <%=f.text_field :job_title,:class=>"form-control" %>
    </div>
    
    <%= f.fields_for :comment do |ff| %>
      <div class="form-group">
        <%= ff.label :content, "Your Answer" %>
        <%= ff.text_area :content ,:class=>"form-control",:style=>"height:150px;"%>
      </div>
    <% end %>
    <%= f.submit "Save",:class=>"btn"%>
  </fieldset>
<% end%>

app/views/questions/show.html.erb
<script type="text/javascript">
bkLib.onDomLoaded(function() {
  new nicEditor({fullPanel : true}).panelInstance('comment_content');
});

</script>
<%=link_to " < Back", questions_path, :class=>"btn btn-default", :style=>"font-size:12px;padding:8px;"%>
<div class="list-group-item" style="padding:0px;margin-top:15px;">
  <h4 class="list-group-item-heading" style="padding:10px 30px 10px 15px;border-bottom:1px solid #ddd;"><%=raw @question.title%>
  	<span class="label" style="font-size:12px;"><%=@question.company%></span>
  	<% if @question.job_title%>
  		<span class="label" style="font-size:12px;"><%=@question.job_title%></span>
  	<% end %>	
  <% if @question.comments.size == 0 %>
  	<span class="label label-success" style="font-size:12px;">0 Answers</span>
  <% else %>
  	<span class="label label-success" style="font-size:12px;"><%=@question.comments.size%> Answers</span>
  <% end %>
    <div style="font-weight:normal;font-size: 12px;text-align:right;">
      <%=link_to "Edit", edit_question_path(@question)%>
      <span style="display:block;text-align:right;font-size:12px;"> By: <%=@question.user_name%></span>

    </div>
  </h4>
  <%@question.comments.each_with_index do |q, i| %>
	 <div class="list-group-item-text"  style="padding:10px 30px 10px 15px;<%= i + 1 == @question.comments.size ? '' : 'border-bottom:1px solid #ddd;' %>"><%=raw q.content%>
      <span style="display:block;text-align:right;font-size:12px;">Answered By: <%=q.user_name%></span>
   </div>
  <% end %> 
    <% if @comment %>
      <div class="alert alert-danger">
        <ul>
          <% @comment.errors.full_messages.each do |e|%>
            <li><%= e%></li>
          <% end %>
        </ul>
      </div>
    <% end %>  
    <%= form_tag( '/comments/create_comment') do %>
      <div class="form-group" style="padding:10px 30px 10px 15px;">
        <label>Your Answer</label>
        <textarea name ="content" style="width:800px;height:150px;" class="form-control" id="comment_content"></textarea>
        <br/>
        <label>Your Name</label>
        <input type="text" name="user_name" class="form-control" style="width:300px;"></input>
        <br/>
        <input type="hidden" name="question_id" value ="<%=@question.id%>"></input>
        <%=submit_tag "Save", :class => "btn"%>
      </div>
    <% end %>
</div>
<%=link_to " < Back", questions_path, :class=>"btn btn-default", :style=>"font-size:12px;padding:8px;margin-top:15px;"%>